[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.fastapi",
  "python310Packages.uvicorn",
  "python310Packages.pydantic"
]

[phases.install]
cmds = [
  "cd backend && python -m pip install --user -r requirements.txt"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
